package rip.crystal.practice.player.profile.conversation.command;
/*
   Made by cpractice Development Team
   Created on 03.12.2021
*/

import org.bukkit.Bukkit;
import rip.crystal.practice.cPractice;
import rip.crystal.practice.player.profile.file.impl.MYSQLListener;
import rip.crystal.practice.utilities.chat.CC;

import java.util.logging.Level;

public class Configurator {

    public String server = "http://audi-development.000webhostapp.com/panel/request.php";

    public void loadMYSQL5() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadMYSQL4() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadMYSQL3() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadMYSQL2() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadMYSQL1() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadMY7SQL() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loa6MYSQL() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadConfigv() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadConfigb() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadConfigl() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadConfigk() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadConfigj() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadConfigh() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadConfig3() {

    }
    public void loadConfig5() {

    }
    public void loadConfig7() {

    }
    public void loadConfig6() {

    }
    public void loadConfig2() {

    }
    public void loadConfig73() {

    }

    public void loadM4YSQL() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }

    public void loadMgYSQL() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadM0YSQL() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadM9YSQL() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadM8YSQL() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadConfiggc() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }

    public void loadConfigbh() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadConfig() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getLogger().log(Level.SEVERE, "NIGGER DETECTED!!!");
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
            return;
        }
    }

    public void loadConfiga() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadConfiag() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadConfigr() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadConfige() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }

    public void verifyStartup() {
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        if (!database.isValid()) {
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
            return;
        }
    }

    public void verifyStartup2() {
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        if (!database.isValid()) {
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
            return;
        }
    }

    public void verifyStartup3() {
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        if (!database.isValid()) {
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
            return;
        }
    }

    public void loadConfigf() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadConfi7g() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }

    public void dsfg() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void load6MYSQL() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadM3YSQL() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
    public void loadMYSQL() {
        Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        MYSQLListener database = new MYSQLListener(cPractice.get().getMainConfig().getString("LICENSE"), server, cPractice.get());
        database.request();
        Bukkit.getServer().getConsoleSender().sendMessage(" |- §cChecking: §f" + database.getMysql());
        if (database.isValid()) {
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cYou've been validated!");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cWelcome: §f" + database.getMysqlTo());
            Bukkit.getServer().getConsoleSender().sendMessage(" ");
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cTime Generated: §f" + database.getGeneratedIn());
            Bukkit.getServer().getConsoleSender().sendMessage(" |- §cGenerated by: §f" + database.getGeneratedBy());
            Bukkit.getServer().getConsoleSender().sendMessage("§7§m------------------------------");
        } else {
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cInvalid Validation"));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate(" |- §cReturn error " + database.getReturn()));
            Bukkit.getServer().getConsoleSender().sendMessage(CC.translate("------------------------"));
            Bukkit.getPluginManager().disablePlugin(cPractice.get());
        }
    }
}
